/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ashkelon (https://sketchfab.com/Ashkelon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/pontiac-600-65317a10cd6c48ffa4a2a4e2904517fd
title: Pontiac 600
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CarModelTwo(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={.9} position={[0,0,-2.4]} rotation={[-Math.PI / 2, 0, -.9]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-70.62, 31.52, -126.95]} rotation={[Math.PI, 0, Math.PI]} scale={148.22}>
            <mesh castShadow receiveShadow geometry={nodes.Wheel003_Wheel_0.geometry} material={materials.Wheel} />
          </group>
          <group position={[-70.62, 31.52, 138.51]} rotation={[Math.PI, 0.56, -Math.PI]} scale={148.22}>
            <mesh castShadow receiveShadow geometry={nodes.Wheel002_Wheel_0.geometry} material={materials.Wheel} />
          </group>
          <group position={[76.19, 31.52, -126.95]} scale={148.22}>
            <mesh castShadow receiveShadow geometry={nodes.Wheel001_Wheel_0.geometry} material={materials.Wheel} />
          </group>
          <group position={[76.19, 31.52, 138.51]} rotation={[0, 0.58, 0]} scale={148.22}>
            <mesh castShadow receiveShadow geometry={nodes.Wheel_Wheel_0.geometry} material={materials.Wheel} />
          </group>
          <group position={[2.81, 16.66, 0.5]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh castShadow receiveShadow geometry={nodes.LowPoly_Material_0.geometry} material={materials.Material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
