/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Alex.Ka. (https://sketchfab.com/Alex.Ka)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/honda-cb-750-f-super-sport-1970-f121301624174b179ca4d50158797b03
title: Honda CB 750 F Super Sport 1970
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BikeModel(props) {
  const { nodes, materials } = useGLTF('/models_glb/scene-honda.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -.7]} position={[1,0,2]} scale={1.11}>
        <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.aluminium} />
        <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials.black_chrome} />
        <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.black_mate} />
        <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.black_chrome} />
        <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.boby} />
        <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials.bolts} />
        <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials.bolts} />
        <mesh castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials.bolts} />
        <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials.chrome} />
        <mesh castShadow receiveShadow geometry={nodes.Object_11.geometry} material={materials.chrome} />
        <mesh castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials.black_chrome} />
        <mesh castShadow receiveShadow geometry={nodes.Object_13.geometry} material={materials.headlights} />
        <mesh castShadow receiveShadow geometry={nodes.Object_14.geometry} material={materials.hondabac} />
        <mesh castShadow receiveShadow geometry={nodes.Object_15.geometry} material={materials.hondaseat} />
        <mesh castShadow receiveShadow geometry={nodes.Object_16.geometry} material={materials.hondaside} />
        <mesh castShadow receiveShadow geometry={nodes.Object_17.geometry} material={materials.lines} />
        <mesh castShadow receiveShadow geometry={nodes.Object_18.geometry} material={materials.mirrors} />
        <mesh castShadow receiveShadow geometry={nodes.Object_19.geometry} material={materials.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_20.geometry} material={materials.material_18} />
        <mesh castShadow receiveShadow geometry={nodes.Object_21.geometry} material={materials.tex_chrome} />
        <mesh castShadow receiveShadow geometry={nodes.Object_22.geometry} material={materials.tex_plastic} />
        <mesh castShadow receiveShadow geometry={nodes.Object_23.geometry} material={materials.material_18} />
        <mesh castShadow receiveShadow geometry={nodes.Object_24.geometry} material={materials.material_18} />
      </group>
    </group>
  )
}

useGLTF.preload('/models_glb/scene-honda.glb')
